services:
  - type: web
    name: brain-brawl-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

databases:
  - name: brain-brawl-db
    plan: free
    type: mongodb
    version: 6.0